### ISSUE TITLE
Getting game by id result in error

### ISSUE THREAD

**Issue by Kareylo** [d-fischer/twitch#21]
## Bug Report

I'm trying to get game data by id and get an error as result

### Code

```ts
// Tryng with id = 493057 (PUBG)
async findGame(id: string) {
    // TWITCH_CLIENT_ID is correctly setted
    this.twitchClient = TwitchClient.withCredentials(process.env.TWITCH_CLIENT_ID || '')
    const gameData = await this.twitchClient.helix.games.getGameById(id)
    return gameData
}
```

### Expected behavior

Getting HelixGame Object

### Actual Behavior

I get this error : 
```
TypeError: Cannot read property 'cursor' of undefined
    at HelixPaginatedRequest.<anonymous> (~/bot/node_modules/twitch/src/API/Helix/HelixPaginatedRequest.ts:37:43)
    at step (~/bot/node_modules/tslib/tslib.js:133:27)
    at Object.next (~/bot/node_modules/tslib/tslib.js:114:57)
    at fulfilled (~/bot/node_modules/tslib/tslib.js:104:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Environment

- Version: 1.0.5
- Node version: 10.13.0
- Operating system: Window 10 Pro

**Comment by d-fischer** [comment]
Fixed in aa05bd6, released as 1.0.6.
