### ISSUE TITLE
helix/streams errors

### ISSUE THREAD

**Issue by T1MOXA** [d-fischer/twitch#25]
### Environment

- Version: 1.3.5
- Node version: v8.15.0
- Operating system: Ubuntu 16.04.5 LTS

### Errors: 
```
 Caught unhandledRejection:  { RequestError: Error: getaddrinfo EAI_AGAIN api.twitch.tv:443
     at new RequestError (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/errors.js:14:15)
     at Request.plumbing.callback (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:87:29)
     at Request.RP$callback [as _callback] (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:46:31)
     at self.callback (/twitch/node_modules/request/request.js:185:22)
     at emitOne (events.js:116:13)
     at Request.emit (events.js:211:7)
     at Request.onRequestError (/twitch/node_modules/request/request.js:881:8)
     at emitOne (events.js:116:13)
     at ClientRequest.emit (events.js:211:7)
     at TLSSocket.socketErrorListener (_http_client.js:401:9)
     at emitOne (events.js:116:13)
     at TLSSocket.emit (events.js:211:7)
     at emitErrorNT (internal/streams/destroy.js:66:8)
     at args.(anonymous function) (/usr/lib/node_modules/pm2/node_modules/event-loop-inspector/index.js:138:29)
     at _combinedTickCallback (internal/process/next_tick.js:139:11)
     at process._tickCallback (internal/process/next_tick.js:181:9)
   name: 'RequestError',
   message: 'Error: getaddrinfo EAI_AGAIN api.twitch.tv:443',
   cause:
    { Error: getaddrinfo EAI_AGAIN api.twitch.tv:443
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
      errno: 'EAI_AGAIN',
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'api.twitch.tv',
      host: 'api.twitch.tv',
      port: 443 },
   error:
    { Error: getaddrinfo EAI_AGAIN api.twitch.tv:443
     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
      errno: 'EAI_AGAIN',
      code: 'EAI_AGAIN',
      syscall: 'getaddrinfo',
      hostname: 'api.twitch.tv',
      host: 'api.twitch.tv',
      port: 443 },
   options:
    { url: 'https://api.twitch.tv/helix/streams',
      headers:
       { Accept: 'application/vnd.twitchtv.v5+json',
         'Client-ID': '***',
         Authorization: 'Bearer ***' },
      qs:
       { community_id: undefined,
         game_id: undefined,
         language: undefined,
         type: undefined,
         user_id: undefined,
         user_login: '***',
         after: undefined,
         first: '100' },
      qsStringifyOptions: { arrayFormat: 'repeat' },
      json: true,
      gzip: true,
      callback: [Function: RP$callback],
      transform: undefined,
      simple: true,
      resolveWithFullResponse: false,
      transform2xxOnly: false },
   response: undefined }
```
   
```
 Caught unhandledRejection:  { RequestError: Error: Parse Error
     at new RequestError (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/errors.js:14:15)
     at Request.plumbing.callback (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:87:29)
     at Request.RP$callback [as _callback] (/twitch/node_modules/request-promise-native/node_modules/request-promise-core/lib/plumbing.js:46:31)
     at self.callback (/twitch/node_modules/request/request.js:185:22)
     at emitOne (events.js:116:13)
     at Request.emit (events.js:211:7)
     at Request.onRequestError (/twitch/node_modules/request/request.js:881:8)
     at emitOne (events.js:116:13)
     at ClientRequest.emit (events.js:211:7)
     at TLSSocket.socketOnData (_http_client.js:459:9)
     at emitOne (events.js:116:13)
     at TLSSocket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at TLSSocket.Readable.push (_stream_readable.js:208:10)
     at TLSWrap.onread (net.js:601:20)
   name: 'RequestError',
   message: 'Error: Parse Error',
   cause: { Error: Parse Error
     at TLSSocket.socketOnData (_http_client.js:454:20)
     at emitOne (events.js:116:13)
     at TLSSocket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at TLSSocket.Readable.push (_stream_readable.js:208:10)
     at TLSWrap.onread (net.js:601:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' },
   error: { Error: Parse Error
     at TLSSocket.socketOnData (_http_client.js:454:20)
     at emitOne (events.js:116:13)
     at TLSSocket.emit (events.js:211:7)
     at addChunk (_stream_readable.js:263:12)
     at readableAddChunk (_stream_readable.js:250:11)
     at TLSSocket.Readable.push (_stream_readable.js:208:10)
     at TLSWrap.onread (net.js:601:20) bytesParsed: 0, code: 'HPE_INVALID_CONSTANT' },
   options:
    { url: 'https://api.twitch.tv/helix/streams',
      headers:
       { Accept: 'application/vnd.twitchtv.v5+json',
         'Client-ID': '****',
         Authorization: 'Bearer ****' },
      qs:
       { community_id: undefined,
         game_id: undefined,
         language: undefined,
         type: undefined,
         user_id: undefined,
         user_login: '***',
         after: undefined,
         first: '100' },
      qsStringifyOptions: { arrayFormat: 'repeat' },
      json: true,
      gzip: true,
      callback: [Function: RP$callback],
      transform: undefined,
      simple: true,
      resolveWithFullResponse: false,
      transform2xxOnly: false },
   response: undefined }
```

**Comment by T1MOXA** [comment]
It seems that the first error because of my DNS server, and does not apply to you, and the second do not know yet...

**Comment by d-fischer** [comment]
Is this reproducible? Can you show code? The issue template is there for a reason.

**Comment by T1MOXA** [comment]
There is a lot of code, and errors occur spontaneously.
So I didn't provide the code.
I'm sorry about that.

**Comment by d-fischer** [comment]
If you don't provide any form of code to reproduce the issue with, I can not tell whether it's a bug in the library or just a (temporary?) issue with your environment.

Please narrow down your problem to a small piece of code that can at least *somewhat* reliably reproduce this bug. Until then, I'm closing it.
